---
- name: Check existing private key
  stat:
    path: "{{ haproxy_ssl_cert_private_key }}"
  register: __private_key_preflight

- name: Check existing private key
  stat:
    path: "{{ haproxy_ssl_cert_public_key }}"
  register: __public_key_preflight

- name: Check existing certificate file
  stat:
    path: "{{ haproxy_ssl_cert_file }}"
  register: __cert_file_preflight

- block: # Prepare HAProxy repository
  - name: Check require packages for custom PPA
    apt:
      name: software-properties-common
      state: present

  - name: Add HAProxy repository
    apt_repository:
      repo: "{{ haproxy_ppa_repository }}"
    when: haproxy_package_name == 'haproxy'
