---
- name: Copy HAProxy configuration file
  template:
    src: "{{ haproxy_host_config_file_path if haproxy_config_check.stat.exists else haproxy_template_file }}"
    dest: "{{ haproxy_cfg_filepath }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart HAProxy Service

- name: Check rsyslog is installed
  apt:
    name: rsyslog
    state: present

- name: Drop rsyslog config
  template:
    src: "{{ rsyslog_template_file }}"
    dest: "{{ rsyslog_filepath }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart Rsyslog Service
